
spring:
  datasource:
  
    url: jdbc:mysql://14.63.166.136:3306/test5?useUnicode=true&characterEncoding=utf-8
    username: pandora_ojt
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  jackson:
    serialization:
      fail-on-empty-beans: false
    
server:
  port: 8085
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
# mybatis 매핑
mybatis:
  type-aliases-package: com.example.demo.dto
  mapper-locations: mybatis/mapper/**/*.xml